spring:
  redis:
    host: 192.168.6.130
    port: 6379
    database: 1
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0




  application:
    name: user


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
