eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



server:
  port: 8085



spring:
  application:
    name: zuul

zuul:
  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: service-ribbon
#    api-b:
#      path: /api-b/**
#      serviceId: config
#      sensitiveHeaders:
    config: /myConfig/**
#    忽略cookie，全部服务就可以接受cookie了，不然zuul默认是不接受cookie的
  sensitive-headers:

#    config: /myconfig/**  //简便写法

# 忽略路由，就是不让他路由
#  ignored-patterns:
#    - /**/service-zuul
#
management:
  security:
    enabled: false











